services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lobo_guara
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data